### PR TITLE
Add Travis CI and Codecov coverage

### LINKED ISSUE #6: Add CI

### PR DESCRIPTION
**Pull request by jpsamaroo**
Closes #6

### CODE REVIEW

**Comment by jpsamaroo** [comment]
@AStupidBear would you be able to setup Travis and Codecov on this repo once you get some time?

**Comment by sosiristseng** [comment]
FYI: Related to #6.

**Comment by jpsamaroo** [comment]
Bump @AStupidBear

**Comment by jpsamaroo** [comment]
Bump @AStupidBear

**Comment by jpsamaroo** [comment]
@AStupidBear we can't reasonably test this repository without CI and code coverage integrations. Both Travis and Codecov/Coveralls/etc. should be free for open source projects like this one.

**Pull request merged**
