### PR TITLE
Support for Adaptive Exponential Integrate and Fire Model.

### PR DESCRIPTION
**Pull request by russelljjarvis**
I love your Spiking Neural Networks package. 

I was thinking it could support Adaptive Exponential models too, so I wrote code for doing that.

I also put a small note in the README.md for developers. Not sure if you would consider it helpful or not.

Russell.

### CODE REVIEW

**Comment by AStupidBear** [comment]
@jpsamaroo Any idea?

**Comment by jpsamaroo** [comment]
The README changes are pretty generic and apply to all Julia packages, so I don't think that change is necessary. New Julia users are generally expected to read the Julia and Pkg docs, which explains how to `dev` a package for development.

Can these commits be squashed? There's quite a lot of "noise".

**Comment by jpsamaroo** [comment]
Also, a stripped down version of the example (without Plots) should be added as a test, to ensure this code actually works.

**Comment by russelljjarvis** [comment]
That all sounds reasonable. I will create a stiped down test version and squash the commits. You are probably write about the documentation.

**Comment by russelljjarvis** [comment]
I closed this issue as adding AdExp is no longer a priority for me.

**Pull request closed without merging**
