### PR TITLE
[WIP] Updates for Julia 1.x

### PR DESCRIPTION
**Pull request by jpsamaroo**
@AStupidBear do you recall where the macros like `@trait`, `@replace`, `@mixin`, and `@symdict` come from?

### CODE REVIEW

**Comment by jpsamaroo** [comment]
@AStupidBear I've gotten all of the tests running (except for stdp_song.jl, because IF2 seems incomplete). If you have some time, I'd appreciate a review to confirm this all looks good.

Additionally, are you willing/able to maintain this package? If not, I'd be happy to take over maintenance on my own fork. I'd like to get this package registered soon so that I can use it for my own machine learning research.

Thanks!

**Comment by jpsamaroo** [comment]
Merged to master at https://github.com/jpsamaroo/SpikingNeuralNetworks.jl

**Comment by AStupidBear** [comment]
@jpsamaroo Could you merge your recent improvements here?

**Comment by AStupidBear** [comment]
@jpsamaroo I have added you to the collaborator.

**Pull request merged**
